# ******** Use the seek Function ********
fp1 = open("F_H_3.txt","w+")
fp1.write("Monday\n")
fp1.write("Tuesday\n")
fp1.write("Wednesday\n")
fp1.write("Thursday\n")
fp1.write("Friday\n")
fp1.seek(0)
print(fp1.read())
fp1.seek(0,2)
fp1.write("Saturday\n")
fp1.write("Sunday\n")
fp1.seek(0)
print(fp1.read())
